def has_dengue():
    if temperature is over 38 degress (Yes/No)
        if fever is occured 2 days or more (Yes/No)
        if it's a sudden fever (Yes/No)
        if fever occurs sunset to sunset or in night time (Yes/No)
    
    if has a headache (Yes/No)
    if has a body pain (Yes/No)
    
    if vomiting occurs (Yes/No)
        if vomiting occurs at least 3 times within 24 hours (Yes/No)
        if has vomiting blood, or blood in the stool (Yes/No)
    
    if Abdominal Pain occurs (Yes/No)
    if has poor appetite (Yes/No)
    
    if has rashes (Yes/No)
        if rashes occurs 2 days or more after fever (Yes/No)
    
    if has pain behind the eyes (Yes/No)
    if has fatigue (Yes/No)
    if has nausea (Yes/No)
    if has mild bleeding such a nose bleed, bleeding gums, or easy bruising (Yes/No)
    if feeling tired, restless, or irritable (Yes/No)
    if has difficult or rapid breathing (Yes/No)
    if has cold or clammy skin (shock) (Yes/No)
    
    if has low WBC (Yes/No)
        if WBC is below 4.5 (Yes/No)
    if has low platelet (Yes/No)
        if platelet is below 150 (Yes/No)
        
def has_gastroenteritis():
    if has fever (Yes/No)
    if diarrhea occurs more than 3 times in one day (Yes/No)
    if has loose stools or watery stools (Yes/No)
    if has incontinence or loss of control over bowel motions (Yes/No)
    if vomiting occurs (Yes/No)
    if abdominal pain occurs (Yes/No)
    if abdominal cramps occurs (Yes/No)
    if body weakness occurs (Yes/No)
    if occasional muscle aches occurs (Yes/No)
    if occasional headace occours (Yes/No)
    if tiredness and general body weakness occurs (Yes/No)
    
def has_tonsilitis():
    if has fever (Yes/No)
    if has sore throat (Yes/No)
    if has chills (Yes/No)
    if has poor appetite or refusing to eat (Yes/No)
    if has red, swollen tonsils (Yes/No)
    if has white or yellow coating or patches on the tonsils (Yes/No)
    if has enlarged tender glands/lymph nodes in the neck (Yes/No)
    if has scratchy, muffled or throaty voice (Yes/No)
    if bad breath occurs (Yes/No)
    if has stiff neck (Yes/No)
    if has headache (Yes/No)
    if has throat pain or tenderness (Yes/No)
    if has difficulty breathing through the mouth (Yes/No)
    if has swollen glands in the neck or jaw area (Yes/No)
    if has pain in the neck (Yes/No)
    if coughing occurs (Yes/No)
    if has furry tounge (Yes/No)
    
def hast_uti():
    if has fever (Yes/No)
    if has stomachache (Yes/No)
    if vomiting occurs (Yes/No)
    if has pain in urethra (Yes/No)
    if has frequent urination (Yes/No)
    if abdominal pain occurs (Yes/No)
    if has Dysuria  or discomfort when urinating(Yes/No)
    if has flank pain (Yes/No)
    if has dark yellow urine (Yes/No)
    if has a burning feeling when urinating (Yes/No)
    if has a frequent or intense urge to urinate, even though little comes out when you do (Yes/No)
    if has a pain or pressure in your back or lower abdomen (Yes/No)
    if has a cloudy, dark, bloody, or strange-smelling urine (Yes/No)
    if feeling tired or shaky (Yes/No)
    if urine appears red, bright pink or cola-colored which is a sign of blood in the urine (Yes/No)
    if has nausea (Yes/No)
    if WBC is to numeros to count (Yes/No)
    if user's Protein is +1 (Yes/No)
    
def has_flu():
    if has fever (Yes/No)
    if has nasal discharge (Yes/No)
    if fever is over 38 degress (Yes/No)
    if has muscle pain (Yes/No)
    if has cough (Yes/No)
    if has dry, persistent cough (Yes/No)
    if has cold (Yes/No)
    if has runny nose (Yes/No)
    if has nasal congestion (Yes/No)
    if has poor appetite (Yes/No)
    if has headache (Yes/No)
    if has chills and sweats (Yes/No)
    if has fatigue (Yes/No)
    if feels weak (Yes/No)
    if has sore throat (Yes/No)
    if has pain and tiredness around the eyes (Yes/No)
    if has trouble breathing or shortness of breathing (Yes/No)
    if has pain or pressure in your chest or belly (Yes/No)
    if has sudden dizziness (Yes/No)
    if has cold sweats and shivers (Yes/No)
